spring:
  h2:
    console:
      enable: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: adm
    driverClassName: org.h2.Driver
  jpa:
    showSql: true
    properties:
      hibernate:
        formatSql: true
